In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
env_training = pd.read_csv("../data/environment_training.csv")
corr_training = pd.read_csv("../data/corrosions_training.csv")

dates = corr_training["observation_date"]

In [3]:
res = pd.merge(env_training, corr_training, on="aircraft_id", how="inner")

In [5]:
res.reset_index()

,index,aircraft_id,year_month,month_start_date,total_parking_minutes,metar_temperature_c,metar_relative_humidity,metar_dew_point_c,metar_wind_speed_kn,metar_visibility_mi,...,nitrogen_monoxide_mass_mixing_ratio,nitrogen_dioxide_mass_mixing_ratio,oh,organic_nitrates,specific_humidity,sulphur_dioxide_mass_mixing_ratio,temperature,observation_date,aircraft_delivery_year,aircraft_delivery_month
0,0,a414b2,2017-04,2017-04-01T00:00:00Z,41220.150000,30.718293,30.899519,9.558831,5.710531,2.196935,...,2.694732e-08,3.239839e-08,9.621187e-14,1.688966e-09,0.007535,5.227935e-08,302.226554,2022-06-29,2016,8
1,1,a414b2,2021-07,2021-07-01T00:00:00Z,28587.733333,29.397745,78.179996,24.765060,6.290009,2.414297,...,6.977001e-09,1.693530e-08,6.740166e-14,8.613307e-10,0.018132,1.506060e-08,301.692884,2022-06-29,2016,8
2,2,41ef34,2024-01,2024-01-01T00:00:00Z,29868.166667,15.522649,76.737610,10.499426,3.765631,1.029053,...,2.471157e-08,4.266760e-08,2.792927e-14,7.472720e-09,0.008187,5.721327e-08,287.567593,2026-04-28,2023,10
3,3,e2d345,2019-05,2019-05-01T00:00:00Z,18139.383333,30.951416,42.349314,15.166188,7.073745,5.594613,...,8.965584e-10,4.222114e-08,1.126736e-13,2.468868e-08,0.014630,1.843788e-08,301.816769,2024-12-03,2015,1
4,4,cfa8ab,2025-07,2025-07-01T00:00:00Z,26916.333333,27.367780,81.524175,23.630275,7.467336,2.774049,...,4.818643e-09,1.728175e-08,7.366147e-14,1.265471e-09,0.018309,1.331511e-08,299.727528,2022-12-10,2017,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63519,63519,661e37,2018-11,2018-11-01T00:00:00Z,43200.000000,12.047059,82.966676,9.064706,6.873529,5.343588,...,2.796081e-09,1.363158e-08,1.128950e-14,1.126368e-09,0.007033,1.470342e-09,285.244050,2024-01-10,2018,5
63520,63520,4b3253,2017-09,2017-09-01T00:00:00Z,43200.000000,27.310231,79.124785,22.943894,3.006579,5.950987,...,3.342279e-11,7.785108e-10,1.736884e-15,1.074707e-09,0.017245,5.628162e-10,301.650542,2019-05-21,2015,5
63521,63521,b8edf3,2018-07,2018-07-01T00:00:00Z,44640.000000,26.648810,79.650060,22.431548,3.413690,6.141250,...,2.182628e-11,5.608379e-10,1.656447e-15,7.825175e-10,0.017126,5.198026e-10,300.423651,2024-04-19,2016,2
63522,63522,2d6473,2025-09,2025-09-01T00:00:00Z,80.266667,26.000000,78.670000,22.000000,2.500000,6.210000,...,7.445210e-11,7.755650e-09,7.959141e-16,4.542368e-09,0.017704,2.995566e-09,299.071251,2024-07-17,2018,8
63523,63523,729344,2017-12,2017-12-01T00:00:00Z,44640.000000,7.292719,82.381461,4.255572,5.872214,4.763789,...,8.935089e-09,1.858380e-08,8.330835e-15,1.097762e-09,0.005325,1.663125e-09,281.094442,2025-01-02,2017,1

In [7]:
res["observation_year"] = res["observation_date"].str.replace(r'-\S+', '', regex=True)

In [8]:
res

,aircraft_id,year_month,month_start_date,total_parking_minutes,metar_temperature_c,metar_relative_humidity,metar_dew_point_c,metar_wind_speed_kn,metar_visibility_mi,metar_hour_precipitation,...,nitrogen_dioxide_mass_mixing_ratio,oh,organic_nitrates,specific_humidity,sulphur_dioxide_mass_mixing_ratio,temperature,observation_date,aircraft_delivery_year,aircraft_delivery_month,observation_year
0,a414b2,2017-04,2017-04-01T00:00:00Z,41220.150000,30.718293,30.899519,9.558831,5.710531,2.196935,0.0,...,3.239839e-08,9.621187e-14,1.688966e-09,0.007535,5.227935e-08,302.226554,2022-06-29,2016,8,2022
1,a414b2,2021-07,2021-07-01T00:00:00Z,28587.733333,29.397745,78.179996,24.765060,6.290009,2.414297,0.0,...,1.693530e-08,6.740166e-14,8.613307e-10,0.018132,1.506060e-08,301.692884,2022-06-29,2016,8,2022
2,41ef34,2024-01,2024-01-01T00:00:00Z,29868.166667,15.522649,76.737610,10.499426,3.765631,1.029053,0.0,...,4.266760e-08,2.792927e-14,7.472720e-09,0.008187,5.721327e-08,287.567593,2026-04-28,2023,10,2026
3,e2d345,2019-05,2019-05-01T00:00:00Z,18139.383333,30.951416,42.349314,15.166188,7.073745,5.594613,0.0,...,4.222114e-08,1.126736e-13,2.468868e-08,0.014630,1.843788e-08,301.816769,2024-12-03,2015,1,2024
4,cfa8ab,2025-07,2025-07-01T00:00:00Z,26916.333333,27.367780,81.524175,23.630275,7.467336,2.774049,0.0,...,1.728175e-08,7.366147e-14,1.265471e-09,0.018309,1.331511e-08,299.727528,2022-12-10,2017,9,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63519,661e37,2018-11,2018-11-01T00:00:00Z,43200.000000,12.047059,82.966676,9.064706,6.873529,5.343588,0.0,...,1.363158e-08,1.128950e-14,1.126368e-09,0.007033,1.470342e-09,285.244050,2024-01-10,2018,5,2024
63520,4b3253,2017-09,2017-09-01T00:00:00Z,43200.000000,27.310231,79.124785,22.943894,3.006579,5.950987,0.0,...,7.785108e-10,1.736884e-15,1.074707e-09,0.017245,5.628162e-10,301.650542,2019-05-21,2015,5,2019
63521,b8edf3,2018-07,2018-07-01T00:00:00Z,44640.000000,26.648810,79.650060,22.431548,3.413690,6.141250,0.0,...,5.608379e-10,1.656447e-15,7.825175e-10,0.017126,5.198026e-10,300.423651,2024-04-19,2016,2,2024
63522,2d6473,2025-09,2025-09-01T00:00:00Z,80.266667,26.000000,78.670000,22.000000,2.500000,6.210000,0.0,...,7.755650e-09,7.959141e-16,4.542368e-09,0.017704,2.995566e-09,299.071251,2024-07-17,2018,8,2024
63523,729344,2017-12,2017-12-01T00:00:00Z,44640.000000,7.292719,82.381461,4.255572,5.872214,4.763789,0.0,...,1.858380e-08,8.330835e-15,1.097762e-09,0.005325,1.663125e-09,281.094442,2025-01-02,2017,1,2025

In [22]:
print(len(res["aircraft_id"].unique()))

758